repos:    
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
        args: ["--ignore=H006,H008,H030,H031,T003"]


  

