repos:
  - repo: https://github.com/rtts/djhtml
    rev: '3.0.10'
    hooks:
      - id: djhtml
      - id: djcss
      - id: djjs
      
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
        args: ["--indent=2"]