repos:    
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django

  - repo: https://github.com/rtts/djhtml
    rev: '3.0.10'
    hooks:
      - id: djcss
      - id: djjs
        entry: djjs --tabwidth 2


  

