repos:    
  - repo: https://github.com/djlint/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
        args: ["--ignore=H006,H008,H030,H031,T003"]

  - repo: https://github.com/rtts/djhtml
    rev: '3.0.10'
    hooks:
      - id: djhtml
        entry: djhtml --tabwidth 2
      - id: djcss
      - id: djjs
        entry: djjs --tabwidth 2


  

