name: Build & Push All Tags to GHCR

on:
  workflow_dispatch:  # Allows manual triggering

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get all tags
        run: |
          git fetch --tags
          git tag -l > tags.txt

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract Docker metadata (tags, labels, etc.)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Loop through each tag and build/push image
      - name: Build & Push Docker images for all tags
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
          for TAG in $(cat tags.txt); do
            echo "Building image for $TAG..."

            # Build the Docker image with metadata
            docker build --build-arg THEME_VERSION=$TAG -t $IMAGE_NAME:$TAG -f docker/Dockerfile .
            
            # Extract tags and labels from metadata-action
            TAGS="${{ steps.meta.outputs.tags }}"
            LABELS="${{ steps.meta.outputs.labels }}"

            # Push the built image to the registry
            docker push $IMAGE_NAME:$TAG

            echo "Pushed image: $IMAGE_NAME:$TAG"
          done
